application: zxing
version: 1
runtime: python
api_version: 1

handlers:
- url: /generator
  script: redirect.py

- url: (.*)/
  static_files: site\1/index.html
  upload: site/index.html

- url: /
  static_dir: site
